spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${SECRET_ID}
            client-secret: ${SECRET_KEY}
            scope:
              - user_posts
              - pages_show_list
              - pages_manage_metadata
              - pages_read_user_content

file:
  upload:
    folder: /home/murad/photos/1

